from copy import deepcopy


INITIAL_WORLD_STATE = {
    "time_step": 0,
    "virtual_week": 0,
    "random_seed": 42,
    "simulation_status": "stopped",
    "products": {
        "sku_standard": {
            "product_id": "sku_standard",
            "name": "Standard Energy Bar Case",
            "unit_type": "case",
            "margin_per_unit": 12.50,
            "estimated_retail_value_per_unit": 30.00,
            "shelf_life_weeks": 20,
            "volume_cubic_meters_per_unit": 1.0,
            "weight_kg_per_unit": 10,
            "stockout_cost_per_unit": 25.00,
            "holding_cost_per_cubic_meter_per_week": 0.15,
            "wastage_cost_per_unit": 8.00,
            "priority": "medium",
        },
        "sku_bulk_pack": {
            "product_id": "sku_bulk_pack",
            "name": "Bulk Retail Pack",
            "unit_type": "case",
            "margin_per_unit": 8.00,
            "estimated_retail_value_per_unit": 42.00,
            "shelf_life_weeks": 20,
            "volume_cubic_meters_per_unit": 3.0,
            "weight_kg_per_unit": 24,
            "stockout_cost_per_unit": 35.00,
            "holding_cost_per_cubic_meter_per_week": 0.15,
            "wastage_cost_per_unit": 10.00,
            "priority": "high",
        },
    },
    "nodes": {
        "domestic_oat_co_op": {
            "node_id": "domestic_oat_co_op",
            "name": "Domestic Oat Co-op",
            "node_type": "sourcing",
            "tier": 0,
            "status": "active",
            "description": "Domestic oat supplier with strong volume economics.",
            "operational_notes": "Cheap, high-volume, seasonal, weather-sensitive.",
            "risk_factors": ["weather", "seasonality", "crop yield"],
            "costs": {"cost_per_unit": 2.10},
            "capacity": {"weekly_capacity_units": 5000},
            "reliability": 0.94,
            "lead_time_variance": 0.20,
        },
        "import_cocoa_port": {
            "node_id": "import_cocoa_port",
            "name": "Import Cocoa Port",
            "node_type": "sourcing",
            "tier": 0,
            "status": "active",
            "description": "Imported cocoa supply routed through ocean freight and customs.",
            "operational_notes": "Long lead times with ocean, customs, and port strike risk.",
            "risk_factors": ["port strike", "customs delay", "ocean disruption"],
            "costs": {"cost_per_unit": 2.80},
            "capacity": {"weekly_capacity_units": 3500},
            "reliability": 0.88,
            "lead_time_variance": 0.55,
        },
        "central_factory": {
            "node_id": "central_factory",
            "name": "Central Factory",
            "node_type": "production",
            "tier": 1,
            "status": "active",
            "description": "Owned production facility with low unit cost and a rigid schedule.",
            "operational_notes": "Cheap but schedule-constrained.",
            "risk_factors": ["locked schedule", "changeover downtime"],
            "active_product_id": "sku_standard",
            "weekly_capacity_units": 3000,
            "production_cost_per_unit": {"sku_standard": 5.25, "sku_bulk_pack": 6.10},
            "schedule_locked_weeks": 2,
            "changeover_delay_weeks": 1,
            "changeover_setup_fee": 6000,
            "current_changeover_remaining_weeks": 0,
            "flexibility_score": "low",
        },
        "co_packer_plant": {
            "node_id": "co_packer_plant",
            "name": "Co-packer Plant",
            "node_type": "production",
            "tier": 1,
            "status": "active",
            "description": "Third-party plant that can flex quickly at higher unit cost.",
            "operational_notes": "Expensive but flexible and fast to activate.",
            "risk_factors": ["third-party capacity", "premium production cost"],
            "active_product_id": "sku_bulk_pack",
            "weekly_capacity_units": 1400,
            "production_cost_per_unit": {"sku_standard": 7.40, "sku_bulk_pack": 8.25},
            "schedule_locked_weeks": 0,
            "changeover_delay_weeks": 0,
            "changeover_setup_fee": 2500,
            "current_changeover_remaining_weeks": 0,
            "flexibility_score": "high",
        },
        "chicago_hub": {
            "node_id": "chicago_hub",
            "name": "Chicago Hub",
            "node_type": "distribution",
            "tier": 2,
            "status": "active",
            "description": "Large rail-connected hub serving bulk retail demand.",
            "operational_notes": "Cheap bulk storage, rail connected, slower outbound fulfillment.",
            "risk_factors": ["rail disruption", "bulk order spikes"],
            "capacity_cubic_meters": 12000,
            "holding_cost_modifier": 0.8,
            "service_channels": ["big_box_retail"],
            "inventory": {
                "sku_standard": [
                    {"age_weeks": 4, "units": 1800},
                    {"age_weeks": 8, "units": 500},
                ],
                "sku_bulk_pack": [
                    {"age_weeks": 3, "units": 900},
                    {"age_weeks": 7, "units": 300},
                ],
            },
        },
        "west_coast_dc": {
            "node_id": "west_coast_dc",
            "name": "West Coast DC",
            "node_type": "distribution",
            "tier": 2,
            "status": "active",
            "description": "Consumer-proximate DC for direct-to-consumer fulfillment.",
            "operational_notes": "Expensive storage, faster consumer delivery.",
            "risk_factors": ["high storage cost", "volatile DTC orders"],
            "capacity_cubic_meters": 7000,
            "holding_cost_modifier": 1.4,
            "service_channels": ["direct_to_consumer"],
            "inventory": {
                "sku_standard": [
                    {"age_weeks": 3, "units": 1800},
                    {"age_weeks": 8, "units": 600},
                ],
                "sku_bulk_pack": [{"age_weeks": 4, "units": 300}],
            },
        },
        "overflow_3pl": {
            "node_id": "overflow_3pl",
            "name": "Overflow 3PL",
            "node_type": "distribution",
            "tier": 2,
            "status": "standby",
            "description": "Optional third-party overflow warehouse for future scenarios.",
            "operational_notes": "Flexible but costly buffer capacity when primary DCs are stressed.",
            "risk_factors": ["premium storage cost", "limited operational visibility"],
            "capacity_cubic_meters": 4000,
            "holding_cost_modifier": 1.8,
            "service_channels": [],
            "inventory": {"sku_standard": [], "sku_bulk_pack": []},
        },
        "big_box_retail": {
            "node_id": "big_box_retail",
            "name": "Big Box Retail",
            "node_type": "demand_channel",
            "tier": 3,
            "status": "active",
            "description": "Bulk retail customer with strict late-shipment penalties.",
            "operational_notes": "Bulk orders, strict service requirements, compliance chargebacks.",
            "risk_factors": ["chargebacks", "retail promotion spikes"],
        },
        "direct_to_consumer": {
            "node_id": "direct_to_consumer",
            "name": "Direct to Consumer",
            "node_type": "demand_channel",
            "tier": 3,
            "status": "active",
            "description": "High-margin but volatile micro-order channel.",
            "operational_notes": "Smaller erratic orders, higher margin, more volatile demand.",
            "risk_factors": ["demand volatility", "same-week fulfillment expectations"],
        },
    },
    "demand_channels": {
        "big_box_retail": {
            "baseline_weekly_demand": {"sku_standard": 1200, "sku_bulk_pack": 900},
            "current_weekly_demand": {"sku_standard": 1200, "sku_bulk_pack": 900},
            "service_level_target": 0.98,
            "priority": "critical",
            "chargeback_rate": 0.15,
            "max_delay_weeks": 1,
            "volatility": 0.06,
            "seasonality_factor": 1.00,
            "served_by": "chicago_hub",
            "description": "Bulk retail customer with strict late-shipment penalties.",
        },
        "direct_to_consumer": {
            "baseline_weekly_demand": {"sku_standard": 1600, "sku_bulk_pack": 200},
            "current_weekly_demand": {"sku_standard": 1600, "sku_bulk_pack": 200},
            "service_level_target": 0.95,
            "priority": "high",
            "max_delay_weeks": 0,
            "volatility": 0.18,
            "seasonality_factor": 1.00,
            "served_by": "west_coast_dc",
            "description": "High-margin but volatile micro-order channel.",
        },
    },
    "lanes": {
        "oat_to_factory_truck": {"lane_id": "oat_to_factory_truck", "origin": "domestic_oat_co_op", "destination": "central_factory", "mode": "truck", "cost_per_unit": 0.35, "transit_weeks": 1, "capacity_units_per_week": 5000, "emissions_per_unit": 0.20, "reliability": 0.93, "status": "active", "current_delay_weeks": 0},
        "cocoa_to_factory_ocean": {"lane_id": "cocoa_to_factory_ocean", "origin": "import_cocoa_port", "destination": "central_factory", "mode": "ocean", "cost_per_unit": 0.22, "transit_weeks": 4, "capacity_units_per_week": 3500, "emissions_per_unit": 0.10, "reliability": 0.86, "status": "active", "current_delay_weeks": 0},
        "factory_to_chicago_rail": {"lane_id": "factory_to_chicago_rail", "origin": "central_factory", "destination": "chicago_hub", "mode": "rail", "cost_per_unit": 0.55, "transit_weeks": 1, "capacity_units_per_week": 3500, "emissions_per_unit": 0.18, "reliability": 0.91, "status": "active", "current_delay_weeks": 0},
        "factory_to_west_truck": {"lane_id": "factory_to_west_truck", "origin": "central_factory", "destination": "west_coast_dc", "mode": "truck", "cost_per_unit": 0.95, "transit_weeks": 1, "capacity_units_per_week": 2200, "emissions_per_unit": 0.42, "reliability": 0.90, "status": "active", "current_delay_weeks": 0},
        "copacker_to_west_truck": {"lane_id": "copacker_to_west_truck", "origin": "co_packer_plant", "destination": "west_coast_dc", "mode": "truck", "cost_per_unit": 0.70, "transit_weeks": 1, "capacity_units_per_week": 1600, "emissions_per_unit": 0.35, "reliability": 0.92, "status": "active", "current_delay_weeks": 0},
        "copacker_to_chicago_truck": {"lane_id": "copacker_to_chicago_truck", "origin": "co_packer_plant", "destination": "chicago_hub", "mode": "truck", "cost_per_unit": 0.85, "transit_weeks": 1, "capacity_units_per_week": 1400, "emissions_per_unit": 0.38, "reliability": 0.90, "status": "active", "current_delay_weeks": 0},
        "copacker_to_overflow_truck": {"lane_id": "copacker_to_overflow_truck", "origin": "co_packer_plant", "destination": "overflow_3pl", "mode": "truck", "cost_per_unit": 1.25, "transit_weeks": 1, "capacity_units_per_week": 1000, "emissions_per_unit": 0.45, "reliability": 0.87, "status": "standby", "current_delay_weeks": 0},
        "chicago_to_big_box_truck": {"lane_id": "chicago_to_big_box_truck", "origin": "chicago_hub", "destination": "big_box_retail", "mode": "truck", "cost_per_unit": 0.45, "transit_weeks": 0, "capacity_units_per_week": 3000, "emissions_per_unit": 0.25, "reliability": 0.94, "status": "active", "current_delay_weeks": 0},
        "west_to_dtc_local": {"lane_id": "west_to_dtc_local", "origin": "west_coast_dc", "destination": "direct_to_consumer", "mode": "local", "cost_per_unit": 0.60, "transit_weeks": 0, "capacity_units_per_week": 2200, "emissions_per_unit": 0.22, "reliability": 0.96, "status": "active", "current_delay_weeks": 0},
        "chicago_to_west_rail": {"lane_id": "chicago_to_west_rail", "origin": "chicago_hub", "destination": "west_coast_dc", "mode": "rail", "cost_per_unit": 0.65, "transit_weeks": 1, "capacity_units_per_week": 2500, "emissions_per_unit": 0.20, "reliability": 0.90, "status": "active", "current_delay_weeks": 0},
        "west_to_chicago_truck": {"lane_id": "west_to_chicago_truck", "origin": "west_coast_dc", "destination": "chicago_hub", "mode": "truck", "cost_per_unit": 1.10, "transit_weeks": 1, "capacity_units_per_week": 1800, "emissions_per_unit": 0.48, "reliability": 0.89, "status": "active", "current_delay_weeks": 0},
        "emergency_air_chicago_to_west": {"lane_id": "emergency_air_chicago_to_west", "origin": "chicago_hub", "destination": "west_coast_dc", "mode": "air", "cost_per_unit": 3.20, "transit_weeks": 0, "capacity_units_per_week": 900, "emissions_per_unit": 1.10, "reliability": 0.97, "status": "active", "current_delay_weeks": 0},
    },
    "graph": {
        "domestic_oat_co_op": ["central_factory"],
        "import_cocoa_port": ["central_factory"],
        "central_factory": ["chicago_hub", "west_coast_dc"],
        "co_packer_plant": ["west_coast_dc", "chicago_hub", "overflow_3pl"],
        "chicago_hub": ["big_box_retail", "west_coast_dc"],
        "west_coast_dc": ["direct_to_consumer", "chicago_hub"],
        "overflow_3pl": [],
    },
    "production_routing": {
        "central_factory": "factory_to_chicago_rail",
        "co_packer_plant": "copacker_to_west_truck",
    },
    "in_transit_shipments": [],
    "constraints": {
        "max_auto_transfer_units": 2500,
        "max_warehouse_utilization": 0.95,
        "warning_warehouse_utilization": 0.90,
    },
    "kpis": {},
    "current_week_transport_cost": 0.0,
    "current_week_emissions": 0.0,
    "current_week_production_cost": 0.0,
    "current_week_changeover_cost": 0.0,
    "current_week_wastage_cost": 0.0,
    "last_unmet_demand": {
        "big_box_retail": {"sku_standard": 0, "sku_bulk_pack": 0},
        "direct_to_consumer": {"sku_standard": 0, "sku_bulk_pack": 0},
    },
    "last_fulfilled_demand": {
        "big_box_retail": {"sku_standard": 0, "sku_bulk_pack": 0},
        "direct_to_consumer": {"sku_standard": 0, "sku_bulk_pack": 0},
    },
    "action_history": [],
    "event_history": [],
    "alert_history": [],
}


WORLD_STATE = deepcopy(INITIAL_WORLD_STATE)


def get_world_state():
    return WORLD_STATE


def reset_world_state():
    global WORLD_STATE
    WORLD_STATE = deepcopy(INITIAL_WORLD_STATE)
    return WORLD_STATE
